export const SET_NOFICATION_VALUE = "SET_NOTIFICATION_VALUE";

//#region Team Members
export const GET_TM_INFO = "GET_TM_INFO";
export const GET_TM_TECH_INFO = "GET_TM_TECH_INFO";
export const GET_TM_POSITION = "GET_TM_POSITION";
export const GET_TM_TIDS_INFO = "GET_TM_TIDS_INFO";
export const GET_TM_TEAM_ASSOC = "GET_TM_TEAM_ASSOC";
export const GET_SKILLS = "GET_SKILLS";
export const GET_PROFICIENCIES = "GET_PROFICIENCIES";
export const CREATE_TM_PROFICIENCY = "CREATE_TM_PROFICIENCY";
export const READ_TM_PROFICIENCY = "READ_TM_PROFICIENCY";
export const UPDATE_TM_PROFICIENCY = "UPDATE_TM_PROFICIENCY";
export const DELETE_TM_PROFICIENCY = "DELETE_TM_PROFICIENCY";
export const GET_JOB_ROLES_CURRENT_TEAM = "GET_JOB_ROLES_CURRENT_TEAM";
export const GET_SKILLS_GAP_CURRENT_ROLE = "GET_SKILLS_GAP_CURRENT_ROLE";
export const GET_SKILLS_GAP_SELECTED_ROLE = "GET_SKILLS_GAP_SELECTED_ROLE";
export const GET_TEAM_SNAPSHOT = "GET_TEAM_SNAPSHOT";
//#endregion

//#region Team Leads
export const GET_TL_TEAM_INFO = "GET_TL_TEAM_INFO";
export const GET_TL_TEAM_MEMBER_COUNT = "GET_TL_TEAM_MEMBER_COUNT";
export const GET_TL_TEAM_SKILLSGAP = "GET_TL_TEAM_SKILLSGAP";
export const GET_PROFICIENCY_APPROVAL_REQUESTS =
  "GET_PROFICIENCY_APPROVAL_REQUESTS";
//#endregion

//#region Managers
export const GET_TEAM_NAMES = "GET_TEAM_NAMES";
export const GET_TEAM_LEAD_NAMES = "GET_TEAM_LEAD_NAMES";
export const GET_RESOURCE_COUNT_PER_SKILL = "GET_RESOURCE_COUNT_PER_SKILL";
export const GET_PROFICIENCY_COUNT_PER_SKILL =
  "GET_PROFICIENCY_COUNT_PER_SKILL";
export const GET_PIVOT_GENERATOR_DATA = "GET_PIVOT_GENERATOR_DATA";
export const GET_HR_TA_INFO = "GET_HR_TA_INFO";
export const GET_SKILL_CATEGORIES = "GET_SKILL_CATEGORIES";
export const GET_CHILD_SKILLS = "GET_CHILD_SKILLS";
export const CREATE_SKILL_CATEGORY = "CREATE_SKILL_CATEGORY";
export const UPDATE_SKILL_CATEGORY = "UPDATE_SKILL_CATEGORY";
export const DELETE_SKILL_CATEGORY = "DELETE_SKILL_CATEGORY";
export const CREATE_SKILL = "CREATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS";
export const GET_ADMIN_SKILLS_GAP = "GET_ADMIN_SKILLS_GAP";
export const UPDATE_TEAM_SNAPSHOT = "UPDATE_TEAM_SNAPSHOT";
export const GET_TEAM_JOBROLE_MANAGER = "GET_TEAM_JOBROLE_MANAGER";
export const GET_TEAM_JOBROLE_SKILL_PROFICIENCY =
  "GET_TEAM_JOBROLE_SKILL_PROFICIENCY";
export const UPDATE_SKILL_PROFICIENCY = "UPDATE_SKILL_PROFICIENCY";
export const ADD_SKILL_PROFICIENCY = "ADD_SKILL_PROFICIENCY";
export const DELETE_SKILL_PROFICIENCY = "DELETE_SKILL_PROFICIENCY";
//#endregion

//#region OneLogin
export const RECEIVE_ACCESS_TOKEN = "RECEIVE_ACCESS_TOKEN";
export const RECEIVE_ID_TOKEN = "RECEIVE_ID_TOKEN";
export const RECEIVE_PROFILE_DATA = "RECEIVE_PROFILE_DATA";
export const GENERATE_STATE_AND_NONCE = "GENERATE_STATE_AND_NONCE";
export const CLEAR_ALL = "CLEAR_ALL";
//#endregion

//#region FUNCTIONAL AREA SNAPSHOT
export const GET_FA_SNAPSHOT = "GET_FA_SNAPSHOT";
export const UPDATE_FA_SNAPSHOT = "UPDATE_FA_SNAPSHOT";
export const GET_FAS = "GET_FAS";
//#end region FUNCTIONAL AREA SNAPSHOT

//#region DASHBOARD
export const ADD_LOGIN_DATA = "ADD_LOGIN_DATA";
export const GET_LOGIN_DATA = "GET_LOGIN_DATA";
export const GET_ALL_TM_TECH_INFO = "GET_ALL_TM_TECH_INFO";
//#endregion DASHBOARD
